### ISSUE TITLE
Identify driver variants

### ISSUE THREAD

**Issue by iskandr** [openvax/neoantigen-vaccine-pipeline#103]
Match all mutations against known specific variants in [CIViC](https://civicdb.org/home) 

Also match non-synonymous coding variants against whitelist of known oncogenes (e.g. TP53, MYC, KRAS, NRAS, &c). 

Plan: use Tier 1 oncogene list from COSMIC: https://cancer.sanger.ac.uk/cosmic/census?tier=1

**Comment by julia326** [comment]
This is being done in Vaxrank now
