### ISSUE TITLE
S04380110_Padded_grch37_with_M.bed not in reference archive

### ISSUE THREAD

**Issue by davidroberson** [openvax/neoantigen-vaccine-pipeline#108]
just found that S04380110_Padded_grch37_with_M.bed is not in the reference archive for testing.  Not that big of a deal because I will test with another bed file.

Also which .yaml file should I use to just do the variant caller steps.

Thank you

**Comment by davidroberson** [comment]
hmm...seems to be stopping after alignment.  I am new to snakemake so maybe I did not specify the output targets correctly?

**Comment by julia326** [comment]
@davidroberson Sorry about that - I'll add the S04380110_Padded_grch37_with_M.bed file to the reference genome. In the current version of the pipeline, it is used only for filtering germline variants, and will not change somatic variant or neoantigen prediction results.

How are you running snakemake, with what arguments? Are you trying to run the entire pipeline or just variant calling? If the latter, you can use https://github.com/openvax/neoantigen-vaccine-pipeline/blob/master/test/idh1_config_dna_only.yaml as a model.

**Comment by julia326** [comment]
Fixed now
