### ISSUE TITLE
Version Docker images

### ISSUE THREAD

**Issue by julia326** [openvax/neoantigen-vaccine-pipeline#75]
Can follow something like this: https://medium.com/travis-on-docker/how-to-version-your-docker-images-1d5c577ebf54

(will need to tweak for our use case, which uses some passwords that we can't store in a build script)

**Comment by iskandr** [comment]
This seems to be done in https://github.com/openvax/neoantigen-vaccine-pipeline/blob/master/docker/VERSION?

**Comment by julia326** [comment]
It is indeed :)
